// Code generated by scripts/generate.py; DO NOT EDIT.
package mixrank

import "context"

// DeleteEmailValidateBulkJobByJobId invokes DELETE /email/validate/bulk-job/{job_id}.
func (c *Client) DeleteEmailValidateBulkJobByJobId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "delete_email_validate_bulk_job_by_job_id", in)
}

// GetAppstoreApps invokes GET /appstore/apps.
func (c *Client) GetAppstoreApps(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps", in)
}

// GetAppstoreAppsByAppId invokes GET /appstore/apps/{app_id}.
func (c *Client) GetAppstoreAppsByAppId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id", in)
}

// GetAppstoreAppsByAppIdConfigs invokes GET /appstore/apps/{app_id}/configs.
func (c *Client) GetAppstoreAppsByAppIdConfigs(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_configs", in)
}

// GetAppstoreAppsByAppIdDownloads invokes GET /appstore/apps/{app_id}/downloads.
func (c *Client) GetAppstoreAppsByAppIdDownloads(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_downloads", in)
}

// GetAppstoreAppsByAppIdIaps invokes GET /appstore/apps/{app_id}/iaps.
func (c *Client) GetAppstoreAppsByAppIdIaps(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_iaps", in)
}

// GetAppstoreAppsByAppIdRankings invokes GET /appstore/apps/{app_id}/rankings.
func (c *Client) GetAppstoreAppsByAppIdRankings(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_rankings", in)
}

// GetAppstoreAppsByAppIdRankingsHistory invokes GET /appstore/apps/{app_id}/rankings-history.
func (c *Client) GetAppstoreAppsByAppIdRankingsHistory(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_rankings_history", in)
}

// GetAppstoreAppsByAppIdRevenue invokes GET /appstore/apps/{app_id}/revenue.
func (c *Client) GetAppstoreAppsByAppIdRevenue(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_revenue", in)
}

// GetAppstoreAppsByAppIdReviews invokes GET /appstore/apps/{app_id}/reviews.
func (c *Client) GetAppstoreAppsByAppIdReviews(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_reviews", in)
}

// GetAppstoreAppsByAppIdSdks invokes GET /appstore/apps/{app_id}/sdks.
func (c *Client) GetAppstoreAppsByAppIdSdks(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_sdks", in)
}

// GetAppstoreAppsByAppIdVersions invokes GET /appstore/apps/{app_id}/versions.
func (c *Client) GetAppstoreAppsByAppIdVersions(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_apps_by_app_id_versions", in)
}

// GetAppstoreDevelopersByDeveloperIdApps invokes GET /appstore/developers/{developer_id}/apps.
func (c *Client) GetAppstoreDevelopersByDeveloperIdApps(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_developers_by_developer_id_apps", in)
}

// GetAppstoreIpaByIpaId invokes GET /appstore/ipa/{ipa_id}.
func (c *Client) GetAppstoreIpaByIpaId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_ipa_by_ipa_id", in)
}

// GetAppstorePrivacyDatatype invokes GET /appstore/privacy/datatype.
func (c *Client) GetAppstorePrivacyDatatype(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_privacy_datatype", in)
}

// GetAppstorePrivacyLabels invokes GET /appstore/privacy/labels.
func (c *Client) GetAppstorePrivacyLabels(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_privacy_labels", in)
}

// GetAppstorePrivacyLinkage invokes GET /appstore/privacy/linkage.
func (c *Client) GetAppstorePrivacyLinkage(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_privacy_linkage", in)
}

// GetAppstorePrivacyPurpose invokes GET /appstore/privacy/purpose.
func (c *Client) GetAppstorePrivacyPurpose(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_privacy_purpose", in)
}

// GetAppstoreRankings invokes GET /appstore/rankings.
func (c *Client) GetAppstoreRankings(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_rankings", in)
}

// GetAppstoreRankingsByContainerByGenreByCountry invokes GET /appstore/rankings/{container}/{genre}/{country}.
func (c *Client) GetAppstoreRankingsByContainerByGenreByCountry(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_rankings_by_container_by_genre_by_country", in)
}

// GetAppstoreSdks invokes GET /appstore/sdks.
func (c *Client) GetAppstoreSdks(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_sdks", in)
}

// GetAppstoreSdksBySdkSlug invokes GET /appstore/sdks/{sdk_slug}.
func (c *Client) GetAppstoreSdksBySdkSlug(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_sdks_by_sdk_slug", in)
}

// GetAppstoreSdksBySdkSlugGenres invokes GET /appstore/sdks/{sdk_slug}/genres.
func (c *Client) GetAppstoreSdksBySdkSlugGenres(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_sdks_by_sdk_slug_genres", in)
}

// GetAppstoreSdksBySdkSlugInstallTrend invokes GET /appstore/sdks/{sdk_slug}/install-trend.
func (c *Client) GetAppstoreSdksBySdkSlugInstallTrend(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_sdks_by_sdk_slug_install_trend", in)
}

// GetAppstoreSdksBySdkSlugInstalls invokes GET /appstore/sdks/{sdk_slug}/installs.
func (c *Client) GetAppstoreSdksBySdkSlugInstalls(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_sdks_by_sdk_slug_installs", in)
}

// GetAppstoreSdksBySdkSlugUninstalls invokes GET /appstore/sdks/{sdk_slug}/uninstalls.
func (c *Client) GetAppstoreSdksBySdkSlugUninstalls(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_sdks_by_sdk_slug_uninstalls", in)
}

// GetAppstoreSdksBySdkSlugVersions invokes GET /appstore/sdks/{sdk_slug}/versions.
func (c *Client) GetAppstoreSdksBySdkSlugVersions(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_appstore_sdks_by_sdk_slug_versions", in)
}

// GetCompanies invokes GET /companies.
func (c *Client) GetCompanies(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies", in)
}

// GetCompaniesByCompanyId invokes GET /companies/{company_id}.
func (c *Client) GetCompaniesByCompanyId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies_by_company_id", in)
}

// GetCompaniesByCompanyIdEmployeeMetrics invokes GET /companies/{company_id}/employee-metrics.
func (c *Client) GetCompaniesByCompanyIdEmployeeMetrics(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies_by_company_id_employee_metrics", in)
}

// GetCompaniesByCompanyIdEmployeeMetricsByJobTagIdTimeseries invokes GET /companies/{company_id}/employee-metrics/{job_tag_id}/timeseries.
func (c *Client) GetCompaniesByCompanyIdEmployeeMetricsByJobTagIdTimeseries(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies_by_company_id_employee_metrics_by_job_tag_id_timeseries", in)
}

// GetCompaniesByCompanyIdTimeseries invokes GET /companies/{company_id}/timeseries.
func (c *Client) GetCompaniesByCompanyIdTimeseries(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies_by_company_id_timeseries", in)
}

// GetCompaniesMatch invokes GET /companies/match.
func (c *Client) GetCompaniesMatch(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies_match", in)
}

// GetCompaniesSegmentPreview invokes GET /companies/segment-preview.
func (c *Client) GetCompaniesSegmentPreview(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies_segment_preview", in)
}

// GetCompaniesSegmentQuery invokes GET /companies/segment-query.
func (c *Client) GetCompaniesSegmentQuery(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_companies_segment_query", in)
}

// GetEcho invokes GET /echo.
func (c *Client) GetEcho(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_echo", in)
}

// GetEmailProspect invokes GET /email/prospect.
func (c *Client) GetEmailProspect(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_email_prospect", in)
}

// GetEmailValidate invokes GET /email/validate.
func (c *Client) GetEmailValidate(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_email_validate", in)
}

// GetEmailValidateBulkJob invokes GET /email/validate/bulk-job.
func (c *Client) GetEmailValidateBulkJob(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_email_validate_bulk_job", in)
}

// GetEmailValidateBulkJobByJobId invokes GET /email/validate/bulk-job/{job_id}.
func (c *Client) GetEmailValidateBulkJobByJobId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_email_validate_bulk_job_by_job_id", in)
}

// GetJobtags invokes GET /jobtags.
func (c *Client) GetJobtags(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_jobtags", in)
}

// GetLinkedinCompany invokes GET /linkedin/company.
func (c *Client) GetLinkedinCompany(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_company", in)
}

// GetLinkedinCompanyPosts invokes GET /linkedin/company/posts.
func (c *Client) GetLinkedinCompanyPosts(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_company_posts", in)
}

// GetLinkedinJob invokes GET /linkedin/job.
func (c *Client) GetLinkedinJob(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_job", in)
}

// GetLinkedinPostBulkJob invokes GET /linkedin/post/bulk_job.
func (c *Client) GetLinkedinPostBulkJob(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_post_bulk_job", in)
}

// GetLinkedinPostBulkJobByJobId invokes GET /linkedin/post/bulk_job/{job_id}.
func (c *Client) GetLinkedinPostBulkJobByJobId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_post_bulk_job_by_job_id", in)
}

// GetLinkedinProfile invokes GET /linkedin/profile.
func (c *Client) GetLinkedinProfile(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_profile", in)
}

// GetLinkedinProfileBulkJob invokes GET /linkedin/profile/bulk_job.
func (c *Client) GetLinkedinProfileBulkJob(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_profile_bulk_job", in)
}

// GetLinkedinProfileBulkJobByJobId invokes GET /linkedin/profile/bulk_job/{job_id}.
func (c *Client) GetLinkedinProfileBulkJobByJobId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_profile_bulk_job_by_job_id", in)
}

// GetLinkedinProfilePosts invokes GET /linkedin/profile/posts.
func (c *Client) GetLinkedinProfilePosts(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_linkedin_profile_posts", in)
}

// GetPersonById invokes GET /person/{id}.
func (c *Client) GetPersonById(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_person_by_id", in)
}

// GetPersonMatch invokes GET /person/match.
func (c *Client) GetPersonMatch(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_person_match", in)
}

// GetPersonSearch invokes GET /person/search.
func (c *Client) GetPersonSearch(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_person_search", in)
}

// GetPersonSegmentPreview invokes GET /person/segment-preview.
func (c *Client) GetPersonSegmentPreview(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_person_segment_preview", in)
}

// GetPersonSegmentQuery invokes GET /person/segment-query.
func (c *Client) GetPersonSegmentQuery(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_person_segment_query", in)
}

// GetPersonSocialUrlLookup invokes GET /person/social-url-lookup.
func (c *Client) GetPersonSocialUrlLookup(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_person_social_url_lookup", in)
}

// GetPlaystoreApksByPackageNameByVersionId invokes GET /playstore/apks/{package_name}/{version_id}.
func (c *Client) GetPlaystoreApksByPackageNameByVersionId(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apks_by_package_name_by_version_id", in)
}

// GetPlaystoreApps invokes GET /playstore/apps.
func (c *Client) GetPlaystoreApps(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps", in)
}

// GetPlaystoreAppsByPname invokes GET /playstore/apps/{pname}.
func (c *Client) GetPlaystoreAppsByPname(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname", in)
}

// GetPlaystoreAppsByPnameImages invokes GET /playstore/apps/{pname}/images.
func (c *Client) GetPlaystoreAppsByPnameImages(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname_images", in)
}

// GetPlaystoreAppsByPnameNamespaces invokes GET /playstore/apps/{pname}/namespaces.
func (c *Client) GetPlaystoreAppsByPnameNamespaces(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname_namespaces", in)
}

// GetPlaystoreAppsByPnameRankings invokes GET /playstore/apps/{pname}/rankings.
func (c *Client) GetPlaystoreAppsByPnameRankings(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname_rankings", in)
}

// GetPlaystoreAppsByPnameRankingsHistory invokes GET /playstore/apps/{pname}/rankings-history.
func (c *Client) GetPlaystoreAppsByPnameRankingsHistory(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname_rankings_history", in)
}

// GetPlaystoreAppsByPnameSdks invokes GET /playstore/apps/{pname}/sdks.
func (c *Client) GetPlaystoreAppsByPnameSdks(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname_sdks", in)
}

// GetPlaystoreAppsByPnameVersions invokes GET /playstore/apps/{pname}/versions.
func (c *Client) GetPlaystoreAppsByPnameVersions(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname_versions", in)
}

// GetPlaystoreAppsByPnameVersionsByVersionCodeApks invokes GET /playstore/apps/{pname}/versions/{version_code}/apks.
func (c *Client) GetPlaystoreAppsByPnameVersionsByVersionCodeApks(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_apps_by_pname_versions_by_version_code_apks", in)
}

// GetPlaystoreDevelopersByDeveloperIdApps invokes GET /playstore/developers/{developer_id}/apps.
func (c *Client) GetPlaystoreDevelopersByDeveloperIdApps(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_developers_by_developer_id_apps", in)
}

// GetPlaystoreRankings invokes GET /playstore/rankings.
func (c *Client) GetPlaystoreRankings(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_rankings", in)
}

// GetPlaystoreRankingsByContainerByCategoryByCountry invokes GET /playstore/rankings/{container}/{category}/{country}.
func (c *Client) GetPlaystoreRankingsByContainerByCategoryByCountry(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_rankings_by_container_by_category_by_country", in)
}

// GetPlaystoreSdks invokes GET /playstore/sdks.
func (c *Client) GetPlaystoreSdks(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_sdks", in)
}

// GetPlaystoreSdksBySdkSlug invokes GET /playstore/sdks/{sdk_slug}.
func (c *Client) GetPlaystoreSdksBySdkSlug(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_sdks_by_sdk_slug", in)
}

// GetPlaystoreSdksBySdkSlugCategories invokes GET /playstore/sdks/{sdk_slug}/categories.
func (c *Client) GetPlaystoreSdksBySdkSlugCategories(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_sdks_by_sdk_slug_categories", in)
}

// GetPlaystoreSdksBySdkSlugDownloads invokes GET /playstore/sdks/{sdk_slug}/downloads.
func (c *Client) GetPlaystoreSdksBySdkSlugDownloads(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_sdks_by_sdk_slug_downloads", in)
}

// GetPlaystoreSdksBySdkSlugInstallTrend invokes GET /playstore/sdks/{sdk_slug}/install-trend.
func (c *Client) GetPlaystoreSdksBySdkSlugInstallTrend(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_sdks_by_sdk_slug_install_trend", in)
}

// GetPlaystoreSdksBySdkSlugInstalls invokes GET /playstore/sdks/{sdk_slug}/installs.
func (c *Client) GetPlaystoreSdksBySdkSlugInstalls(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_sdks_by_sdk_slug_installs", in)
}

// GetPlaystoreSdksBySdkSlugUninstalls invokes GET /playstore/sdks/{sdk_slug}/uninstalls.
func (c *Client) GetPlaystoreSdksBySdkSlugUninstalls(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_playstore_sdks_by_sdk_slug_uninstalls", in)
}

// GetSegmentFeaturesBySegment invokes GET /segment-features/{segment}.
func (c *Client) GetSegmentFeaturesBySegment(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_segment_features_by_segment", in)
}

// GetSegmentResult invokes GET /segment-result.
func (c *Client) GetSegmentResult(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_segment_result", in)
}

// GetTwitterQueryByQueryIds invokes GET /twitter/query/{query_ids}.
func (c *Client) GetTwitterQueryByQueryIds(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_twitter_query_by_query_ids", in)
}

// GetUsage invokes GET /usage.
func (c *Client) GetUsage(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_usage", in)
}

// GetWebSites invokes GET /web/sites.
func (c *Client) GetWebSites(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_web_sites", in)
}

// GetWebSitesByDomain invokes GET /web/sites/{domain}.
func (c *Client) GetWebSitesByDomain(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_web_sites_by_domain", in)
}

// GetWebSitesByDomainTags invokes GET /web/sites/{domain}/tags.
func (c *Client) GetWebSitesByDomainTags(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_web_sites_by_domain_tags", in)
}

// GetWebTags invokes GET /web/tags.
func (c *Client) GetWebTags(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_web_tags", in)
}

// GetWebTagsBySlug invokes GET /web/tags/{slug}.
func (c *Client) GetWebTagsBySlug(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_web_tags_by_slug", in)
}

// GetWebTagsBySlugSites invokes GET /web/tags/{slug}/sites.
func (c *Client) GetWebTagsBySlugSites(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "get_web_tags_by_slug_sites", in)
}

// PostCompaniesSegmentPreview invokes POST /companies/segment-preview.
func (c *Client) PostCompaniesSegmentPreview(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_companies_segment_preview", in)
}

// PostCompaniesSegmentQuery invokes POST /companies/segment-query.
func (c *Client) PostCompaniesSegmentQuery(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_companies_segment_query", in)
}

// PostEmailValidateBulkJob invokes POST /email/validate/bulk-job.
func (c *Client) PostEmailValidateBulkJob(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_email_validate_bulk_job", in)
}

// PostIdentityIngest invokes POST /identity/ingest.
func (c *Client) PostIdentityIngest(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_identity_ingest", in)
}

// PostLinkedinPostBulkJob invokes POST /linkedin/post/bulk_job.
func (c *Client) PostLinkedinPostBulkJob(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_linkedin_post_bulk_job", in)
}

// PostLinkedinProfileBulkJob invokes POST /linkedin/profile/bulk_job.
func (c *Client) PostLinkedinProfileBulkJob(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_linkedin_profile_bulk_job", in)
}

// PostPersonSegmentPreview invokes POST /person/segment-preview.
func (c *Client) PostPersonSegmentPreview(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_person_segment_preview", in)
}

// PostPersonSegmentQuery invokes POST /person/segment-query.
func (c *Client) PostPersonSegmentQuery(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_person_segment_query", in)
}

// PostPrivacyRedactionRequest invokes POST /privacy-redaction-request.
func (c *Client) PostPrivacyRedactionRequest(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_privacy_redaction_request", in)
}

// PostTwitterProfileByHandler invokes POST /twitter/profile/{handler}.
func (c *Client) PostTwitterProfileByHandler(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_twitter_profile_by_handler", in)
}

// PostTwitterQueryByQuery invokes POST /twitter/query/{query}.
func (c *Client) PostTwitterQueryByQuery(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "post_twitter_query_by_query", in)
}

// SearchCompanies invokes POST /elasticsearch/companies/_search.
func (c *Client) SearchCompanies(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "search_companies", in)
}

// SearchIndustries invokes POST /elasticsearch/industries/_search.
func (c *Client) SearchIndustries(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "search_industries", in)
}

// SearchJobs invokes POST /elasticsearch/jobs/_search.
func (c *Client) SearchJobs(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "search_jobs", in)
}

// SearchOrgName invokes POST /elasticsearch/org_name/_search.
func (c *Client) SearchOrgName(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "search_org_name", in)
}

// SearchPerson2 invokes POST /elasticsearch/person2/_search.
func (c *Client) SearchPerson2(ctx context.Context, in Request) (*Response, error) {
	return c.Call(ctx, "search_person2", in)
}
