#!/usr/bin/env python3
"""Generate SDK methods and portable references from the sanitized catalog."""
import json,pathlib,re,subprocess,sys
root=pathlib.Path(__file__).resolve().parents[1];cat=json.loads((root/'catalog/endpoints.json').read_text())
outputs={};go=['// Code generated by scripts/generate.py; DO NOT EDIT.','package mixrank','import "context"']
md=['# MixRank operation reference','','Generated from catalog version '+cat['version']+'.','',f"{len(cat['operations'])} operations visible in the authorized documentation, including five Elasticsearch searches. Licensing still determines which calls may succeed.",'','Use `mixrank api <command> --help` for flags. All parameters are strings on the wire; JSON bodies preserve numeric precision. `--query KEY=VALUE` passes additional documented query fields.','']
for op in cat['operations']:
 name=''.join(w[:1].upper()+w[1:] for w in op['id'].split('_'));cmd=op['id'].replace('_','-')
 go += [f'// {name} invokes {op["method"]} {op["path"]}.',f'func (c *Client) {name}(ctx context.Context, in Request) (*Response,error) {{ return c.Call(ctx,"{op["id"]}",in) }}']
 md += ['## '+cmd,'',f'`{op["method"]} {op["path"]}` — {op["summary"]}', '',f'Encoding: {op["encoding"]}. Pagination: {op["pagination"]}. Automatic replay eligible: {str(op["safe_retry"]).lower()} (refresh can further restrict this).', '',op.get('notes',''),'']
 if op['parameters']:
  md += ['| Parameter | Location | Required | Default / range / values |','|---|---|---|---|']
  for p in op['parameters']:
   details='; '.join(k+'='+str(p[k]) for k in ['default','min','max','enum'] if k in p).replace('|','\\|')
   md.append(f'| `{p["name"]}` | {p["in"]} | {str(p["required"]).lower()} | {details} |')
  md.append('')
 if op['response_fields']:md+=['Response fields: '+', '.join('`'+p['path']+'` ('+p['type']+')' for p in op['response_fields'])+'.','']
 md += ['Sources: '+', '.join('[provider contract]('+s+')' for s in op['sources'])+'. Verified '+op['verified']+'.','']
outputs['operations_gen.go']='\n'.join(go)+'\n';outputs['skills/mixrank-cli/references/operations.md']='\n'.join(md)+'\n'
# Installed skills carry their references with them.
for f in (root/'catalog/mappings').glob('*.json'):outputs['skills/mixrank-knowledge/references/'+f.name]=f.read_text()
check='--check' in sys.argv
for path,data in outputs.items():
 target=root/path
 if path.endswith('.go'):
  data=subprocess.run(['gofmt'],input=data,text=True,capture_output=True,check=True).stdout
 if check:
  if not target.exists() or target.read_text()!=data:sys.exit('Stale generated file: '+path)
 else:target.parent.mkdir(parents=True,exist_ok=True);target.write_text(data)
print('Generated files current' if check else 'Generated '+str(len(outputs))+' files')
